spring:
  application:
    name: tour-package-be

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  profiles: 
    active: 'dev'

  jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        adjust-dates-to-context-time-zone: true
      time-zone: Asia/Jakarta

  datasource:
    url: jdbc:postgresql://localhost:35001/tour-pacakage-dev
    username: tour-package-dev
    password: CLI-825.2025X

  jpa:
    hibernate:
      ddl-auto: create-drop
